### ISSUE TITLE
Docker Build for linux/arm64/v8

### ISSUE THREAD

**Issue by gimse** [pandosme/timelapse-server#1]
Hi. I want to run the app on a raspberry pi with Docker, but it is not built for linux/arm64/v8. 

Can you build the docker image for linux/arm64/v8 ?

**Comment by pandosme** [comment]
Yes I could do that.  I can also provide the dockerfile if you woukd like that./FredSkickat från min Galaxy
-------- Originalmeddelande --------Från: Gimse ***@***.***> Datum: 2024-08-25  18:02  (GMT+01:00) Till: pandosme/timelapse-server ***@***.***> Kopia: Subscribed ***@***.***> Ämne: [pandosme/timelapse-server] Docker Build for linux/arm64/v8 (Issue #1) 
Hi. I want to run the app on a raspberry pi with Docker, but it is not built for linux/arm64/v8.
Can you build the docker image for linux/arm64/v8 ?

**Comment by pandosme** [comment]
I will publish it on Github.  The image is Node-RED and ffmpeg.  The source is the Node-RED flows./FredSkickat från min Galaxy
-------- Originalmeddelande --------Från: Gimse ***@***.***> Datum: 2024-08-26  12:42  (GMT+01:00) Till: pandosme/timelapse-server ***@***.***> Kopia: Fred Juhlin ***@***.***>, Comment ***@***.***> Ämne: Re: [pandosme/timelapse-server] Docker Build for linux/arm64/v8 (Issue #1) 
That would be awesome :)
Do you have the source-code available?

**Comment by pandosme** [comment]
I just made the timelapse-docker public.  I hope this is sufficient for you to create the container for armv7hf.  Or, if you are a Node-Redder, use the package.json and flows.json on a Node-RED on the host. Install ffmpeg to enable the application to generate MP4.

/Fred
________________________________

**Comment by gimse** [comment]
Thank you, so much. I will check it out as soon I have the opportunity :)
